// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6LJeWoTxfeOunYioUjn_eMPYzelX33UU',
    appId: '1:261584102580:web:3da0e243940016553623e1',
    messagingSenderId: '261584102580',
    projectId: 'food-delivery-c6811',
    authDomain: 'food-delivery-c6811.firebaseapp.com',
    storageBucket: 'food-delivery-c6811.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-txYHN662r-ZadhlJl80xfAKiy537ZeY',
    appId: '1:261584102580:android:2f462460d6ff9bf13623e1',
    messagingSenderId: '261584102580',
    projectId: 'food-delivery-c6811',
    storageBucket: 'food-delivery-c6811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB33L-Errr2BtYZXSnN-NI-UV5uqveLM1o',
    appId: '1:261584102580:ios:c5151fbeb1ea70063623e1',
    messagingSenderId: '261584102580',
    projectId: 'food-delivery-c6811',
    storageBucket: 'food-delivery-c6811.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB33L-Errr2BtYZXSnN-NI-UV5uqveLM1o',
    appId: '1:261584102580:ios:c5151fbeb1ea70063623e1',
    messagingSenderId: '261584102580',
    projectId: 'food-delivery-c6811',
    storageBucket: 'food-delivery-c6811.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6LJeWoTxfeOunYioUjn_eMPYzelX33UU',
    appId: '1:261584102580:web:3b044d4b502901be3623e1',
    messagingSenderId: '261584102580',
    projectId: 'food-delivery-c6811',
    authDomain: 'food-delivery-c6811.firebaseapp.com',
    storageBucket: 'food-delivery-c6811.appspot.com',
  );
}
